# Site title
title = "NEXUSlab"

# Publish directory
publishDir = "docs"

# hostname (and path) to the root
baseurl = "/"

# Remark if you want to disable multilingual support.
DefaultContentLanguage = "en"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = ""

[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"

[author]
name = "haydex"
email = "hayddex@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#

[params.theme]
name = "flatly"

[params.popover]
# This is a highly configurable popover form.
enablepopover = false #enable or disable popover: true/false.
posturl = "https://zapier.com/hooks/catch/1227563/" # Your zapier post hook.
headerimage = "//placehold.it/1000x600"
expirecookie = 5 #show it again after number of days to visitors that has not subscribed.
cookiename = "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
signupheader = "Join Our Newsletter"
showmodaltimeout = 10000 #show popover modal after time interval in milliseconds.
mouseleave = true #show popover when mouse leaves window: true/false.
modalsize = "" #lg or sm. Empty is md. If phone is detected lg is used.
imagedescription = "Placeholder image for this popover modal optin form"
signuptext = "Signup today for free and be the first to get notified on new updates."
inputplaceholder = "Enter your email"
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
errormessage = "Submitting form failed!"
optin = true #opt-in: true/false

[params]
# menu for changing language. This changes languages with js and stores the choice with the help of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the md files needs to have the same name for each language abbreviation to work correctly. Example: showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
switchlang = false
# You can use markdown here.
BrandImage = "/nexuslablogo.png" #top header brand image.
brand = "NEXUSlab" # brand image alt text.
topline = "few words about your site"
toplink = ""
footline = "</br>EIT Building Rm 565</br>College of Engineering and Information Technology</br>University of Arkansas at Little Rock</br>2801 S University Avenue</br>Little Rock, Arkansas 72204-1099</br></br>"
pager = "true"
fullTitle = "Networked and Complex Systems Security Research (NEXUS) Lab"

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "home"

mailmunchid = "" # Mailmunch site id
# sumomeid = ""

# Show a sidebar menu
showRightSidebar = false
# Select a syntax highlight.
# Check the static/css/highlight directory for options.
highlight = "default"

# Google Analytics.
googleAnalytics = "Your Google Analytics tracking code"

# Sidebar social links.
github = "Myprofile" # Your Github profile ID
bitbucket = "" # Your Bitbucket profile ID
linkedin = "" # Your LinkedIn profile ID (from public URL)
googleplus = "Myprofile" # Your Google+ profile ID
facebook = "Myprofile" # Your Facebook profile ID
twitter = "Myprofile" # Your Twitter profile ID
youtube = ""  # Your Youtube channel ID
flattr = ""  # populate with your flattr uid

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

# Menus
# If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
# like this:
#[menu]
#     [menu.main]
#        name = "Showcase"
#        weight = 3
#        identifier = "showcase"
# i18n menus. A menu will be added for each language to the right in the top menu. This menu will switch to the selected language. Remember to add the corresponding language in pathnamereplace.js.
#[[Languages.sv.menu.switchlang]]
#  name = "English"
#  identifier = ""
#  weight = 4
#  url = "en"

[Languages]
[Languages.en]
languageCode = "en"
weight = 1
copyright = "(c) 2017 Copyright NEXUSlab"